// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Premium.Calculator.Persistence.Contexts.PremiumCalculator;

namespace Premium.Calculator.Persistence.Migrations
{
    [DbContext(typeof(PremiumCalculatorDbContext))]
    [Migration("20201018051558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Premium.Calculator.Domain.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeathSumInsured")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccupationId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Premium.Calculator.Domain.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupationRatingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccupationRatingId");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("Premium.Calculator.Domain.OccupationRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Factor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OccupationRatings");
                });

            modelBuilder.Entity("Premium.Calculator.Domain.Customer", b =>
                {
                    b.HasOne("Premium.Calculator.Domain.Occupation", "Occupation")
                        .WithMany("Customers")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Premium.Calculator.Domain.Occupation", b =>
                {
                    b.HasOne("Premium.Calculator.Domain.OccupationRating", "OccupationRating")
                        .WithMany("Occupations")
                        .HasForeignKey("OccupationRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
